apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: podinfo
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  interval: 1h
  path: ./kustomize
  prune: false
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: podinfo
