apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kyverno-controller
  namespace: flux-system
spec:
  interval: 2h
  provider: generic
  url: oci://ghcr.io/kyverno/manifests/kyverno
  ref:
    tag: "v1.8.1"
  verify:
    provider: cosign
