apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-controller
  namespace: flux-system
spec:
  interval: 4h
  sourceRef:
    kind: OCIRepository
    name: kyverno-controller
  serviceAccountName: kustomize-controller
  path: ./
  prune: true
  wait: true
  timeout: 5m
