---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/swapnild2111/fluxcd-prune-issue
  ref:
    branch: flux-cd-examples
  secretRef:
    name: github-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kyverno-policies
    namespace: flux-system
  interval: 1h
  retryInterval: 5m
  path: ./clusters/local/modules/kyverno-policies/policies
  prune: true
  timeout: 2m
  dependsOn:
    - name: kyverno-controller
